// Machine-readable names for the failures a storefront has to react to.
//
// The `message` beside them is English and meant for developers and
// logs; a Persian storefront translates the CODE. Matching on message
// text would break the moment a sentence is reworded, which is exactly
// the kind of breakage nobody notices until a customer sees an English
// error.
export const ErrorCodes = {
  // Generic, derived from the HTTP status when nothing more specific
  // was thrown.
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Catalogue and stock
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  VARIANT_REQUIRED: 'VARIANT_REQUIRED',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_NOT_FOR_SALE: 'VARIANT_NOT_FOR_SALE',
  DUPLICATE_VARIANT_COMBINATION: 'DUPLICATE_VARIANT_COMBINATION',
  REQUIRED_ATTRIBUTE_MISSING: 'REQUIRED_ATTRIBUTE_MISSING',
  INVALID_ATTRIBUTE_VALUE: 'INVALID_ATTRIBUTE_VALUE',

  // Checkout
  SHIPPING_METHOD_REQUIRED: 'SHIPPING_METHOD_REQUIRED',
  SHIPPING_METHOD_UNAVAILABLE: 'SHIPPING_METHOD_UNAVAILABLE',
  PAYMENT_METHOD_REQUIRED: 'PAYMENT_METHOD_REQUIRED',
  COD_NOT_SUPPORTED: 'COD_NOT_SUPPORTED',
  COD_LIMIT_EXCEEDED: 'COD_LIMIT_EXCEEDED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  ORDER_NOT_EDITABLE: 'ORDER_NOT_EDITABLE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // Money
  INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
  WALLET_INACTIVE: 'WALLET_INACTIVE',
  PAYMENT_GATEWAY_UNAVAILABLE: 'PAYMENT_GATEWAY_UNAVAILABLE',
  AMOUNT_TOO_LARGE: 'AMOUNT_TOO_LARGE',

  // Discounts
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  DISCOUNT_EXHAUSTED: 'DISCOUNT_EXHAUSTED',
  DISCOUNT_NOT_STARTED: 'DISCOUNT_NOT_STARTED',
  DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
  DISCOUNT_MIN_ORDER_NOT_MET: 'DISCOUNT_MIN_ORDER_NOT_MET',
  DISCOUNT_USER_LIMIT_REACHED: 'DISCOUNT_USER_LIMIT_REACHED',
  DISCOUNT_NOT_APPLICABLE: 'DISCOUNT_NOT_APPLICABLE',

  // Accounts
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  OTP_INCORRECT: 'OTP_INCORRECT',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',

  // Returns
  RETURN_WINDOW_CLOSED: 'RETURN_WINDOW_CLOSED',
  RETURN_NOT_ALLOWED: 'RETURN_NOT_ALLOWED',
  RETURN_QUANTITY_EXCEEDED: 'RETURN_QUANTITY_EXCEEDED',
  REFUND_EXCEEDS_PAID: 'REFUND_EXCEEDS_PAID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

// What the filter falls back to when a plain Nest exception was thrown.
export const STATUS_FALLBACK_CODES: Record<number, ErrorCode> = {
  400: ErrorCodes.BAD_REQUEST,
  401: ErrorCodes.UNAUTHORIZED,
  403: ErrorCodes.FORBIDDEN,
  404: ErrorCodes.NOT_FOUND,
  409: ErrorCodes.CONFLICT,
  429: ErrorCodes.TOO_MANY_REQUESTS,
};
