export const MAX_MONEY_AMOUNT = 1_000_000_000;

export const DEFAULT_PAYMENT_WINDOW_MINUTES = 15;

export const PAYMENT_UNKNOWN_GRACE_HOURS = 24;

export const MAX_OPEN_PAYMENT_SESSIONS_PER_USER = 3;
